pipeline {
    agent {
        docker {
            image 'maven:3.8.1-adoptopenjdk-11'
        }
    }

    stages {
        stage('Run App') {
            steps {
                dir('java-app') {
                    sh 'mvn compile exec:java'
                }
            }
        }
    }
}
